USE beerme_db;
SELECT * FROM beers;
INSERT INTO beers (beername,category, reviews, rating)
VALUES ("Pacifico","Pilsner","This beer is really good and authentic",4),
("Anchor Liberty Ale","IPA", "From a can, this 'hazy, juicy, dry-hopped' beer pours a very hazy, golden color with a big, fluffy off-white head.",5 ),
("Negra Modelo", "Lager", "Best black beer from a bottle",4),
("Guinnes", "Stout", "This is a Guinnes beer!", 5),
("Victory Prima Pilsner Beers", "Pilsner", "Using a mix of German and Czech hops and malts, it is one of the most traditional brews on this list.",4),
 ("Bluejacket","Lager","This is thanks to the unique open fermentation process using both lager and farmhouse yeast.", 4),
("Stone IPA", "IPA", "This beers is tro strong for me it made be cray cray", 3),
("SixPoint The Crisp", "Pilsner", "Brooklyn beauty features a floral, grassy aroma leading into nice bready malt and light lemon before a dry, peppery finish.",4),
("Notch Session Pils", "Pilsner", "A worker’s beer but I can attest that it’s perfectly suited to serve as a well, actually just kind of a blogger’s beer too, as it has landed in my fridge at least twice as often as any other beer over the past four years.", 5),
("Firestone Walker Pivo Pils", "Pilsner", "Pivo is both excellent and authentic: The style sticklers at the Great American Beer Festival have awarded Pivo the gold medal in the German-style pilsner category all three years that the Magnum-, Spalter-, and Saphir-hopped wonderbrew has existed", 5),
("North Coast Scrimshaw", "Pilsner", "I am cursed to live in a benighted region where it is not always easy to find fresh bottles of this clean, crisp 4.7-percent ABV German-style pilsner from Fort Bragg, California, but I snap it up every chance I get.", 5),
("Victory Prima Pils", "Pilsner", "This critically acclaimed 5.3-percent ABV pilsner has a beautiful balance between pale, crackery malt and floral, herbal hops.", 4),
("Half Acre Pony", "Pilsner", "At 5.8-percent ABV, this aggressive Chicagoan pushes the upper limits of the category, but there’s no hint of undue alcohol in the smooth, pepper-heavy flavor.", 4),
("Deschutes Pine Mountain", "Pilsner", "Of all the bigger breweries that don’t distribute to my state, I think I might pick Deschutes if I were allowed to choose the next party-crasher.",4),
("Shell's Pilsner", "Pilsner", "Though ales continue to dominate the American craft beer market, more and more lagers are coming to light as sophisticated drinkers drop their Bud-flavored biases and brewers seek ways to differentiate themselves.", 4),
("Avery Joe's Pils", "Pilsner", "This 4.7-percent ABV classic from Boulder, Colorado, stands out as crisp and clean even in a style practically defined by those attributes.", 5),
("Heater Allen Pils", "Pilsner", "I have to confess that I’ve only had this Oregon product once, and I either didn’t take notes or I’ve lost them.", 5),
("Sweetwater Georgia Brown", "Brown Ale", "This English brown ale exudes malty, roasted notes, with a less chocolatey caramel presence than most brown ales. For a more crisp, clean- finished brown ale, this one’s for you.", 5),
("Durty Mud Season", "Brown Ale", "This hoppier brown ale provides a pleasant bitterness to the beer, with strong malty flavors that balance the piney hoppiness. Unique and satisfying all at once.", 5),
("Brooklyn Brown Ale", "Brown Ale", "This medium-bodied, creamy brown ale presents a more oaty, bread-like palate with a tangy sweet finish. A solid, standard brown ale.", 4),
("Wormtown Brewry Blizzard", "Brown Ale", "This English-style brown ale is brewed with fresh roasted coffee beans, hence the strong coffee-like, roasted aromas. Coffee, roasted malt, and toasty nuttiness dominate the palate, making this a perfect beer for a chillier spring day.", 4),
("Founders Sumatra Mountain", "Brown Ale", "This American brown ale is extremely powerful, with bold maltiness and caramel flavors dominating the palate. Chocolate, aromatic, and Munich malts are all used in the brewing process, creating a layered, balanced mouthfeel. Sumatra coffee adds a deliciously decadent kick.", 5),
("Cigar City Brewing Maduro", "Brown Ale", "Dark brown with toffee aromas, this bready brown ale shows hints of espresso and nutty maltiness, with just the right amount of carbonation. Another solid choice from Cigar City.", 5),
("Ithaca Beer Company Nut Brown Ale", "Brown Ale", "Dark amber in color, this English brown ale is medium-bodied with nutty, bread-like flavors. Chocolate and caramel notes are moderate, making this surprisingly smooth brew extremely drinkable.", 4),
("Newcastle Brown Ale", "Brown Ale", "If all else fails, grab the OG of English brown ales. Brewed by Heineken, this simple, nutty beer shows earthy notes and slight bitterness, with an extremely smooth finish.", 4),
("Stone Smoked Porter", "Porter", "At the forefront of many beer styles, Stone is usually present or closely adjacent. Their smoked porter is no different. Always inventive, in 2012 Stone held a vote to determine if fans preferred their Vanilla Bean or Chipotle Pepper variations on their porter.", 5),
("Maui Coconut Porter", "Porter", "Maybe it’s their high-priced cans or obscure styles, but we think that Maui Brewing is quite underrated when it comes to craft breweries in America.", 5),
("Wingman P-51 Porter", "Porter", "Just 30 miles south of Seattle, a burgeoning beer giant, is the city of Tacoma, and home of Wingman Brewing. P-51 Porter is one of Wingman’s flagship brews, and is one of the best straight forward porters available on the West Coast.", 5),
("Caldera Mogli Porter", "Porter", "This oak-aged porter is brewed with chocolate, and chocolate is present on the palate from aroma to taste. This beer has a higher alcohol content than is typical in porters (8.5 percent), and also carries a higher price tag.", 4),
("Founders Porter", "Porter", "In a similar vain to what Stone Brewing is on the West Coast, Michigan-based Founders Brewing finds their beers atop several lists of great beers from a variety of styles. Founders Porter is a great example of the blurred lines between porters and stouts.", 4),
("Deschutes Black Butte Porter", "Porter", "Not every porter is wild and crazy. Not every porter has to be aged on some special kind of wood. Not every porter needs to be infused with some sort of sweetener or spice.", 4),
("Great Lakes Edmund", "Porter", "One of the preeminent breweries in the midwest themselves. Edmund Fitzgerald porter ranks high on the list of Great Lakes Brewing’s beer. Along with a hearty porter, Edmund Fitzgerald offers a history lesson.", 4),
("Ballast Point Victory at Sea Coffe", "Porter", "One commonality among many of the best porters, is that they stray quite substantially from the standard definition of a porter. Victory at Sea is very high in alcohol (10.0 percent), and pours dark black with a fruity nose that isn’t common among porters.", 5),
("Highland Oatmeal Porter", "Porter", "Nestled in North Carolina, Highland Oatmeal Porter offers many of the flavors one would expect with a traditional porter. In addition to traditional flavors, this porter offers an earthiness from the infusion of oatmeal while mashing.", 4),
("Almanac Bourbon Sour Porter", "Porter", "We are the first ones to admit – sour beers are not for everyone. Though dark in color, this sour porter provides surprising tartness. ", 4),
("St. Clair Brown Honey", "Wheat Beer", "Beautifully cloudy in the glass, St. Clair Brown’s Honey Wheat has lemony, saison-like aromas.", "4"),
("Odell Brewing Easy Street", "Wheat Beer", "Almost opaque and sunset-gold, this unfiltered American wheat is a year-round offering from Odell — for good reason.", 4),
("21st Amendment Hell or High Watermelon", "Wheat Beer", "This summer seasonal brewed with watermelon puree was a hit among our panel’s melon lovers, though some found it less lovable.", 4),
("Avery Brewing White Rascal", "Wheat Beer", "Zesty, delicious, and traditional with a twist, White Rascal purrs with Belgian yeast-driven aromas and flavors of banana and clove, reminiscent of a hefeweizen without being filling or overt.", 4),
("Bell's Oberon", "Wheat Beer", "Translucent as an orange wedge and topped with a fluffy, off-white head, Bell’s Oberon drew our panelists in with its lemony citrus and spicy yeast aromas.", 5),
("Highland Brewing Stargazer", "Wheat Beer", "Brushed gold in color with a fluffy white head, Highland pulls off a classic white with Stargazer. “Smells like beer — and Belgian yeast,” one taster noted, praising its simplicity.", 5),
("Finback Double Sess", "Wheat Beer", "For those who like their spices front and center, Finback’s Double Sess(ion) is it. The most interesting of the mix, this beer pours a cloudy yellow and has bold aromas of ginger, Szechuan peppers, chamomile, and zippy citrus.", 5),
("Wiley Roots Super 77 American", "Wheat Beer", "Wiley Roots offers a deliciously crisp wheat ale with a flavorful edge. Pouring a cloudy gold and bursting with fruity and sweet cereal-grain aromas, it reminded one taster of a bowl of cereal with berries, but in balanced beer form.", 5),
("Allagash White", "Wheat Beer", "Pouring the cloudiest, palest of straw yellow with a bright white head, Allagash White is peak witbier. Pepper, clove, and lemon aromas fill the nose, followed by light-bodied crisp refreshment from a perfected grain bill of oats, both malted and unmalted raw wheat, along with Nugget, Crystal, and Czech Saaz hops.", 5),
("Magnetron Black Lager", "Dark Lager", "being pleasantly surprised is a memorable experience. For some pretty good reasons, here in the States, we have the impression that the blacker a beer is, the heavier, boozier, viscous, etc.", 4),
("1554 Black Lager", "Dark Lager", "New Belgium 1554 pours a gorgeous mahogany with malt accompanied by subtle notes of fruit, herb, spice, and coffee.", 4),
("Baba Black Lager", "Dark Lager", "Baba, a five-time medal-winning and certified organic black lager, includes a few attributes common to smoked porters.", 4),
("Smoke & Dagger Black Lager", "Dark Lager", "It has a great mouthfeel, not too heavy and not too light which makes it very drinkable and a good gateway to other beers of this variety.", 4),
("Shiner 97 Bohemian Black Lager", "Dark Lager", "Visually, Shiner 97 is a twin to stout beer with an opaque black color and tan head. However, the light-bodied dark lager can be consumed like cold water on a hot day.", 4),
("Commentator Doppelbock", "Dark Lager", "It’s slightly sweet, low in bitterness, and finishes with a pleasant, clean toasty caramel flavor that leaves you wanting more. Doppelbocks are not as roasty as an imperial stout, they don’t have as much bitterness as an American barleywine.", 4),
("Munich Dunkel", "Dark Lager", "Despite the flavors, this beer does not offer an overly sweet impression, but rather a mild balance between malt sweetness and hop character.", 4),
("Sierra Nevada", "Pale Ale", "This is the godfather of pale ales. The APA G.O.A.T., if you will… Without it, craft beer would not be what it is today.", 4),
("El Segundo Brewing Company", "Pale Ale", "A bronze medal winner at the 2010 GABF. Nice and malty, with a creamy mouthfeel.", 4),
("Citra Extra Pale", "Pale Ale", "A lighter pale ale, dry-hopped with Citra. If it featured more of a malt backbone, it would be higher up on our list.", 4),
("Third Street Aleworks", "Pale Ale", "This sweet pale ale offers a clean finish with a nip of Simcoe pithy hop bitterness. Another sessionable pale ale that works in any season.", 4),
("Stone Brewing Co.", "Pale Ale", "A definite improvement over the original 1.0. Sweet plummy aroma, with mildly carbonated body closer to an amber ale in color.", 4),
("Drake’s Brewing Company", "Pale Ale", "This coppery ale starts a little malty sweet, then the dry hopped-ness kicks in for the finish. There are citrus elements to this ale.", 4),
("Foothills Sexual Chocolate", "Stout", "The Foothills gang out of Winston-Salem knew this cocoa-infused imperial stout was phenomenal, so they had to bless it with one of the dopest packages in the game.", 4),
("Good People El Gordo", "Stout", "Birmingham is progressively establishing itself as a must-visit beer city, and Good People certainly played a DiCaprio-level role in that. Inspired by the popular Mexican luchadores.", 4),
("Grand Teton Black Cauldron", "Stout", "Available throughout the West, Midwest, and some eastern states -- use their beer locator tool here
Probably one of the most widely available imperial stouts and perhaps Idaho’s favorite limited specialty beer release is Grand Teton’s Black Cauldron imperial stout.", 4),
("Goose Island Reserve Bourbon County Stout", "Stout", "The hotly anticipated Black Friday release of Goose Island's Bourbon County stout and its assorted variants was bigger than ever -- literally, the eight varieties on the seminal stout.", 4),
("Crux Fermentation Project Tough Love", "Stout", "Crux founder Larry Sidor is famous for, among other things, being Deschutes Brewery’s brewmaster for eight years, during which time he created the now infamous The Abyss imperial stout.", 4),
("Perennial Artisan Ales Abraxas", "Stout", "Adding chiles can be a dangerous game when it comes to beer -- add too little and why did you even bother, go too heavy and your beer will be memorable.", 4),
("Duchesse de Bourgogne","Wild Sour Ale","Brewed by Verhaeghe in Belgium, this traditional sour Flanders Red is 100% natural, unpasteurized and, fittingly, makes the top of our list.", 4),
("Westbrook Gose","Wild Sour Ale","The Westbrook Brewing company is based in South Carolina, and they were one of the first to resurrect this traditional German wheat beer.", 4),
("New Belgium La Folie","Wild Sour Ale","It’s packed with rich fruit flavors, including cherry and green apple, for an extra bit of acidity. At 7% ABV, this is not for the timid palate.", 4),
("New Glarus Raspberry Tart","Wild Sour Ale","What is wonderful about this beer is that it’s traditionally brewed through spontaneous fermentation for a more authentic sour flavor.", 4),
("Rodenbach Fruitage","Wild Sour Ale","With a very high fruit content of 9% and a blend of young and old aged sours, it provides a wonderful combination of sweet and sour at a perfect 4.2% ABV.", 4),
("Goose Island Gillian","Wild Sour Ale","Along with that punch, it has an amazing combination of sour ale, strawberries, and honey, which are added to the fermentation process at different stages.", 4),
("Lost Nation Gose","Wild Sour Ale","The very dry finish of this craft beer from Vermont follows traditional German Gose techniques using coriander and salt.", 4),
("Hacker-Pschorr Oktoberfest Märzen","German Black", "Made by one of the Oktoberfest breweries, Märzen was traditionally an end-of-brewing-season beer, made a little bit stronger to help them last through to the autumn festivals", 4),
("Schneider Weisse Tap","German Black", "A legendary German beer brewed with wheat and dark malts. It’s full-bodied, subtly sweet, smooth and creamy, and peppered with spiciness from the yeast and hops.", 4),
("Weihenstephan Hefe Weissbier","German Black", "Top notch Hefeweizens from Erdinger and Franziskaner have been readily available in British supermarkets for years, and we’ve started noticing increased shelf space for Weihenstephan’s version too.", 4),
("Fruh Kolsch","German Black", "Cologne’s beer style, Kölsch, is a pale ale bordering on lager territory and Früh’s version is as refreshing as it comes.", 4),
("Augustiner Helles","German Black", "Few countries can match Germany’s lager brewing brilliance, with the country’s malt and hops perfectly suited to the crisp, clean characteristics of a good lager.", 4),
("White Ghost Berliner Weisse","German Black", "Stone Brewing started life in California, 1996, and twenty years later their impressive growth enabled them to open a brewery in Berlin.", 4),
("Brauerie Heller","German Black", "One sniff is all it takes to reveal a Rauchbier’s special ingredient: smoked malt. This beer, a Bamberg speciality, is chestnut brown with a good depth of malty flavours, strong bittering and a shaving of oaky maturity.", 4),
("Sticke Altbier","German Black", "Altbier is a Dusseldorf speciality – a style that uses top-fermenting ale yeast and receives a long conditioning period at a low temperature, to create a brown ale that has a smoother, more lagerish feel than traditional British brown ales.", 4),
("Dogfish Head", "Indian Pale Ale", "This is a popular and strong IPA choice set of Delaware United States. This is otherwise known as an Imperial IPA or American double IPA.", 4),
("Le Trou Du Diable", "Indian Pale Ale", "This beer is produced in Canada and it stands as one of the top IPAs in the world. This IPA was named the best IPA in the world for the year 2015 and won many international awards.", 4),
("Sierra Nevada Torpedo", "Indian Pale Ale", "I included Sierra Nevada Torpedo on the list as it is currently one of the top-selling IPAs in the United States.", 4),
("Todd the axe man", "Indian Pale Ale", "It is best known for its flavors of passion fruit, citrus as well as a deep bitterness that comes from a unique style of pops.", 4),
("Lush Hop IPA", "Indian Pale Ale", "This is one of the most balanced IPA’s in the entire world and it was the winner for the top Asian IPA this past year.", 4),
("Saranac Legacy IPA", "Indian Pale Ale", "This 6.5% ABV IPA is produced in New York state and is known for its wide appeal across the US.", 4),
("Brewdog Punk IPA", "Indian Pale Ale", "This pale beer has become a quick favorite across Europe and although it is a craft beer still, it can be fairly accessible as well.", 4),
("King Julius", "Indian Pale Ale", "If you like light and smooth citrus flavors as well as heavy hops, King Julius will be your new favorite IPA and something to emulate in your own beer making.", 4),
("Westmalle Tripel", "Belgian Style Ale", "If one beer could represent Belgium’s vast brewing output, it would probably be Westmalle’s Tripel: a Trappist blond ale brewed to a high strength.", 4),
("De Ranke XX Bitter", "Belgian Style Ale", "This is a golden Belgian beer with the malt levels turned down a notch and the hop count set to high.", 4),
("Duvel Tripel Hop Citra", "Belgian Style Ale", "The golden sparkle and clean, crisp taste of a chilled Duvel has put it at the top of many drinkers’ best-beer lists for decades, but recently the brewers have started to play with its classic ale.", 4),
("De Struise Brouwers ", "Belgian Style Ale", "De Struise is one of Belgium’s most influential modern breweries, giving old techniques such as barrel-ageing and blending a contemporary twist with some highly experimental beers. ", 4),
("Rodenbach Grand Cru", "Belgian Style Ale", "This Flemish red ale is a complicated beast, a blend of two thirds aged in oak foeders for two years and a third comprising younger beer.", 4),
("Fantôme Saison", "Belgian Style Ale", "The traditional French and Belgian farmhouse saison is now brewed the world over, with the style morphing into many forms, so we had to find room for a classic Belgian offering in our list.", 4),
("Boon Oude Geuze", "Belgian Style Ale", "If you can track them down, geuzes – a blend of old and new Lambics – from Cantillon and 3 Fonteinen are worthy of attention,", 4),
("St Bernardus Wit", "Belgian Style Ale", "Belgian wit beers are brewed with wheat and spiced with coriander and orange peel, and this offering, from a brewery that started out as a cheese factory, is as good as it gets.", 4),
("Weihenstephaner", "Specialty Beer", "offers up the notes of banana and clove that we’d expect, but also adds in touches of warm ripe orange, dried apricot, and fresh white peach.",4),
("The Answer Brewpub", "Specialty Beer", "While The Answer has been unapologetic about their approach, going so far as to design crowler labels that look like bombs with a ticking timer on them to underscore",4),
("3 Fonteinen Oude Geuze", "Specialty Beer", "With lambic brewing and blending, time is as much an ingredient as terroir, and Cuvée Armand & Gaston was a long time coming for one of Belgium’s leading lambic producers. ",4),
("Fort George Brewery", "Specialty Beer", "It’s year six for this rotating yearly collaboration IPA from Oregon Coast powerhouse Fort George, and the 2018 edition lived up to the high expectations set by all of the prior editions.",4),
("von Trapp Brewing", "Specialty Beer", "Following the installation of a brand new starte-of-the-art brewhouse in Stowe, Vermont, a few years ago, the brewers at von Trapp have been turning out high-caliber lagers in the Old World ",4),
("Suarez Family Brewery", "Specialty Beer", "Great beer takes time to make...and to pour as well. Dan Suarez, the brewer behind the namesake brewery, cares about the time it takes to make beer right, and it shows with everything they make",4),
("Anchorage Brewing A Deal", "Specialty Beer", "The flavors are both intense yet superbly integrated, with the rich caramel, molasses, and burnt-sugar base you’d expect from a barleywine, but none of the vegetal or dry-wood character",4),
("Burial Beer Hawkbil", "Specialty Beer", "Our annual IPA issue is the toughest competition we see all year, as hundreds of breweries vie for attention in the most-sold style in craft beer. ",4)








